# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
    pod 'Fabric', '1.9.0'
    pod 'Crashlytics', '3.12.0'
    pod 'MBProgressHUD', '1.1.0'
    pod 'Alamofire', '4.8.2'
end

target '___PACKAGENAME___' do
    shared_pods
end
