#!/bin/bash

projectTemplateDeploymentScript="./Scripts/install_project_template.sh"
fileTemplateDeploymentScript="./Scripts/install_file_template.sh"
UserDataDeploymentScript="./Scripts/install_user_data.sh"

repoUrl="http://10.0.0.192/git/xcode_project_template/repository/archive.zip"
repoZipFileName="xcode_project_template-master"

main() {

	if [ $SHOULD_UPDATE = false ] ; then
		show_error
		exit
	fi

	echo "Downloading content from repository..."
	curl_res=$(curl -LSs $repoUrl -o /tmp/$repoZipFileName.zip -w %{http_code} --connect-timeout 30)
	if [ ! -z "$curl_res" ] && [ $curl_res -eq 200 ]
	then
		echo "Downloaded"
	else
		echo "Terminating script execution due to error in downloading..."
		exit
	fi

	echo "Unzipping content..."
	unzip -a "/tmp/$repoZipFileName.zip" -d "/tmp/"

	cd "/tmp/$repoZipFileName"*/

	sh $projectTemplateDeploymentScript $repoZipFileName

	sh $fileTemplateDeploymentScript $repoZipFileName

	sh $UserDataDeploymentScript $repoZipFileName

	echo -e "\n\n\n"
	echo "Cleaning up after ourself..."
	rm -R "/tmp/$repoZipFileName"*

	echo "INSTALLATION COMPLETED..."
}

show_error() {
 echo "Error: Please use -u flag to update xcode seed project."
}

SHOULD_UPDATE=false

while getopts ':u' flag; do
  case "${flag}" in
	u) SHOULD_UPDATE=true ;;
    *) show_error; exit; ;;
  esac
done

# run scripts
main