source 'http://10.0.0.192/git/TP-Pod-Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!

def shared_pods
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MBProgressHUD'
    pod 'TPHttpRequestManager'
end

target '___PACKAGENAME___' do
    shared_pods
end
